products:
  - name: Mediacom Brand Reporting Gold
    title: Example product silver
    description: |
      Silver version of the example product
    quota: 2
    interval: 1
    timeunit: minute
    proxies:
      - echoheaders
    openapi: swagger.json
categories:
  - name: category1
    openapi: swagger.json
    products:
      - id: 1234
        inheritSpec: true
      - id: 4321
        inheritSpec: false
        openapi: swagger.json
